"""initial_schema

Revision ID: 5d3772683a2b
Revises: 
Create Date: 2026-06-10 10:33:39.543949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3772683a2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_file_id', sa.Integer(), nullable=False),
    sa.Column('start_time_seconds', sa.Float(), nullable=False),
    sa.Column('end_time_seconds', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('phone_call_id', sa.Integer(), nullable=True),
    sa.Column('correlation_confidence', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_segments_id'), 'call_segments', ['id'], unique=False)
    op.create_index(op.f('ix_call_segments_phone_call_id'), 'call_segments', ['phone_call_id'], unique=False)
    op.create_index(op.f('ix_call_segments_uploaded_file_id'), 'call_segments', ['uploaded_file_id'], unique=False)
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_id'), 'operators', ['id'], unique=False)
    op.create_index(op.f('ix_operators_operator_code'), 'operators', ['operator_code'], unique=True)
    op.create_table('processed_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_file_id', sa.Integer(), nullable=False),
    sa.Column('call_segment_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('start_time_seconds', sa.Float(), nullable=False),
    sa.Column('end_time_seconds', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_processed_clips_call_segment_id'), 'processed_clips', ['call_segment_id'], unique=False)
    op.create_index(op.f('ix_processed_clips_id'), 'processed_clips', ['id'], unique=False)
    op.create_index(op.f('ix_processed_clips_uploaded_file_id'), 'processed_clips', ['uploaded_file_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('recording_date', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('RECEIVED', 'ANALYZING', 'COMPLETED', 'FAILED', name='processingstate'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_operator_id'), 'uploaded_files', ['operator_id'], unique=False)
    op.create_table('phone_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(length=100), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_calls_call_id'), 'phone_calls', ['call_id'], unique=True)
    op.create_index(op.f('ix_phone_calls_id'), 'phone_calls', ['id'], unique=False)
    op.create_index(op.f('ix_phone_calls_start_time'), 'phone_calls', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_calls_start_time'), table_name='phone_calls')
    op.drop_index(op.f('ix_phone_calls_id'), table_name='phone_calls')
    op.drop_index(op.f('ix_phone_calls_call_id'), table_name='phone_calls')
    op.drop_table('phone_calls')
    op.drop_index(op.f('ix_uploaded_files_operator_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_processed_clips_uploaded_file_id'), table_name='processed_clips')
    op.drop_index(op.f('ix_processed_clips_id'), table_name='processed_clips')
    op.drop_index(op.f('ix_processed_clips_call_segment_id'), table_name='processed_clips')
    op.drop_table('processed_clips')
    op.drop_index(op.f('ix_operators_operator_code'), table_name='operators')
    op.drop_index(op.f('ix_operators_id'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_call_segments_uploaded_file_id'), table_name='call_segments')
    op.drop_index(op.f('ix_call_segments_phone_call_id'), table_name='call_segments')
    op.drop_index(op.f('ix_call_segments_id'), table_name='call_segments')
    op.drop_table('call_segments')
    # ### end Alembic commands ###
